// Private podcast feed. Only feed.xml is served by an HTTP action; audio bytes
// come from storage URLs rewritten onto the public host. A wrong token is a
// 404 so the route is invisible to scanners.
import { v } from "convex/values";
import { internalQuery, query } from "./_generated/server";
import { requireAuth } from "./auth";

export type FeedEpisode = {
  id: string;
  title: string;
  createdAt: number;
  durationSecs?: number;
  sizeBytes: number;
  mimeType: string;
  storageUrl: string;
};

const FEED_LIMIT = 100;

export async function feedTokenMatches(
  pathToken: string,
  expected: string | undefined,
): Promise<boolean> {
  if (!expected || !pathToken) return false;
  // Compare fixed-size SHA-256 digests: the work done depends only on the
  // caller's own input plus a constant, so neither the comparison nor its
  // timing reveals the expected token's length or content.
  const [a, b] = await Promise.all([digest(pathToken), digest(expected)]);
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= (a[i] ?? 0) ^ (b[i] ?? 0);
  return diff === 0;
}

async function digest(text: string): Promise<Uint8Array> {
  const bytes = new TextEncoder().encode(text);
  return new Uint8Array(await crypto.subtle.digest("SHA-256", bytes));
}

const DEFAULT_PUBLIC_BASE_URL = "https://listen.rproj.art";

// Shared with the feed route so the subscription URL and the enclosure URLs
// always name the same host.
export function podcastPublicBaseUrl(): string {
  return process.env.PODCAST_PUBLIC_BASE_URL || DEFAULT_PUBLIC_BASE_URL;
}

export type PodcastSubscription =
  | { configured: true; feedUrl: string }
  | {
      configured: false;
      reason: "missing_token" | "invalid_token" | "invalid_base_url";
    };

// The route compares the raw path segment, so a token needing percent-encoding
// could never match; such a token is reported rather than handed out.
const URL_SAFE_TOKEN = /^[A-Za-z0-9._~-]+$/;

export function podcastSubscription(
  token: string | undefined,
  publicBaseUrl: string,
): PodcastSubscription {
  if (!token) return { configured: false, reason: "missing_token" };
  if (!URL_SAFE_TOKEN.test(token)) {
    return { configured: false, reason: "invalid_token" };
  }
  let base: URL;
  try {
    base = new URL(publicBaseUrl);
  } catch {
    return { configured: false, reason: "invalid_base_url" };
  }
  if (base.protocol !== "https:" && base.protocol !== "http:") {
    return { configured: false, reason: "invalid_base_url" };
  }
  const root = `${base.origin}${base.pathname.replace(/\/$/, "")}`;
  return { configured: true, feedUrl: `${root}/podcast/${token}/feed.xml` };
}

// The feed URL is a bearer credential: only an authenticated caller gets it,
// and nothing here logs it or puts it in an error.
export const subscription = query({
  args: { devBypassSecret: v.optional(v.string()) },
  returns: v.union(
    v.object({ configured: v.literal(true), feedUrl: v.string() }),
    v.object({
      configured: v.literal(false),
      reason: v.union(
        v.literal("missing_token"),
        v.literal("invalid_token"),
        v.literal("invalid_base_url"),
      ),
    }),
  ),
  handler: async (ctx, args): Promise<PodcastSubscription> => {
    await requireAuth(ctx, args);
    return podcastSubscription(
      process.env.PODCAST_FEED_TOKEN,
      podcastPublicBaseUrl(),
    );
  },
});

export function publicStorageUrl(
  storageUrl: string,
  publicBaseUrl: string,
): string {
  const parsed = new URL(storageUrl);
  return `${publicBaseUrl.replace(/\/$/, "")}${parsed.pathname}`;
}

function escapeXml(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

const DEFAULT_FEED_DESCRIPTION =
  "Private episodes generated by Frequency Music.";

export function buildFeedXml(args: {
  title: string;
  publicBaseUrl: string;
  episodes: FeedEpisode[];
  description?: string;
}): string {
  const items = [...args.episodes]
    .toSorted((a, b) => b.createdAt - a.createdAt)
    .slice(0, FEED_LIMIT)
    .map((episode) => {
      const url = publicStorageUrl(episode.storageUrl, args.publicBaseUrl);
      const duration =
        episode.durationSecs === undefined
          ? ""
          : `<itunes:duration>${Math.round(episode.durationSecs)}</itunes:duration>`;
      return [
        "<item>",
        `<title>${escapeXml(episode.title)}</title>`,
        `<guid isPermaLink="false">${escapeXml(episode.id)}</guid>`,
        `<pubDate>${new Date(episode.createdAt).toUTCString()}</pubDate>`,
        `<enclosure url="${escapeXml(url)}" length="${episode.sizeBytes}" type="${escapeXml(episode.mimeType)}"/>`,
        duration,
        "</item>",
      ].join("");
    })
    .join("\n");
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">',
    "<channel>",
    `<title>${escapeXml(args.title)}</title>`,
    `<link>${escapeXml(args.publicBaseUrl)}</link>`,
    `<description>${escapeXml(args.description ?? DEFAULT_FEED_DESCRIPTION)}</description>`,
    "<language>en-us</language>",
    "<itunes:author>Freq</itunes:author>",
    "<itunes:block>yes</itunes:block>",
    "<itunes:explicit>false</itunes:explicit>",
    '<itunes:category text="Music"/>',
    items,
    "</channel>",
    "</rss>",
  ].join("\n");
}

export const listFeedEpisodes = internalQuery({
  args: { limit: v.optional(v.number()) },
  handler: async (ctx, args): Promise<FeedEpisode[]> => {
    const rows = await ctx.db
      .query("audioArtifacts")
      .withIndex("by_access_kind_createdAt", (q) =>
        q.eq("access", "feed").eq("kind", "episode"),
      )
      .order("desc")
      // Only ready deliveries count toward the limit: pending or failed
      // episodes newer than the ready ones must not push them out of the
      // window, and neither may the feed-access WAV master every episode
      // job also writes (with `limit: 1` a newer master would hide the
      // delivery it belongs to).
      .filter((q) =>
        q.and(
          q.eq(q.field("status"), "ready"),
          q.eq(q.field("role"), "delivery"),
        ),
      )
      .take(args.limit ?? FEED_LIMIT);
    const episodes: FeedEpisode[] = [];
    for (const row of rows) {
      // Defense in depth: a blind-group member is never served in the feed,
      // whatever its access value says, and neither is a WAV master (only the
      // delivery encode is an episode).
      if (!row.storageId || row.blindGroupId || row.role !== "delivery") {
        continue;
      }
      const storageUrl = await ctx.storage.getUrl(row.storageId);
      const meta = await ctx.db.system.get(row.storageId);
      if (!storageUrl || !meta) continue;
      episodes.push({
        id: row._id,
        title: row.title,
        createdAt: row.createdAt,
        durationSecs: row.durationSecs,
        sizeBytes: meta.size,
        mimeType: row.mimeType ?? "audio/mpeg",
        storageUrl,
      });
    }
    return episodes;
  },
});
