import { convexTest } from "convex-test";
import { afterEach, describe, expect, test, vi } from "vite-plus/test";
import { modules } from "../harness/modules";
import { internal } from "./_generated/api";
import { buildFeedXml, feedTokenMatches, publicStorageUrl } from "./podcast";
import schema from "./schema";
import type { AudioArtifactInput } from "./shared/audioArtifacts";

describe("podcast feed", () => {
  test("token match is exact regardless of length", async () => {
    expect(await feedTokenMatches("abc", "abc")).toBe(true);
    expect(await feedTokenMatches("ab", "abc")).toBe(false);
    expect(await feedTokenMatches("abcd", "abc")).toBe(false);
    expect(await feedTokenMatches("abc%20", "abc")).toBe(false);
    expect(await feedTokenMatches("", "")).toBe(false);
    expect(await feedTokenMatches("abc", undefined)).toBe(false);
  });

  test("storage urls are rewritten onto the public host", () => {
    expect(
      publicStorageUrl(
        "http://convex.rproj.art:3211/api/storage/0123-abcd",
        "https://listen.rproj.art",
      ),
    ).toBe("https://listen.rproj.art/api/storage/0123-abcd");
  });

  test("feed renders items newest first with enclosures and escapes text", () => {
    const xml = buildFeedXml({
      title: "Frequency Music, private",
      publicBaseUrl: "https://listen.rproj.art",
      episodes: [
        {
          id: "k1",
          title: "Weekly turn, week of 2026-09-21 & more",
          createdAt: 1_700_000_000_000,
          durationSecs: 600,
          sizeBytes: 9_600_000,
          mimeType: "audio/mpeg",
          storageUrl: "http://convex.rproj.art:3211/api/storage/one",
        },
        {
          id: "k2",
          title: "Older",
          createdAt: 1_600_000_000_000,
          durationSecs: 60,
          sizeBytes: 960_000,
          mimeType: "audio/mpeg",
          storageUrl: "http://convex.rproj.art:3211/api/storage/two",
        },
      ],
    });
    expect(xml.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(xml).toContain("<itunes:block>yes</itunes:block>");
    expect(xml).toContain(
      "<description>Private episodes generated by Frequency Music.</description>",
    );
    expect(xml).toContain("&amp; more");
    expect(xml.indexOf("api/storage/one")).toBeLessThan(
      xml.indexOf("api/storage/two"),
    );
    expect(xml).toContain(
      'url="https://listen.rproj.art/api/storage/one" length="9600000" type="audio/mpeg"',
    );
    expect(xml).toContain('<guid isPermaLink="false">k1</guid>');
    expect(xml).toContain("<itunes:duration>600</itunes:duration>");
  });

  test("empty feed is still valid", () => {
    const xml = buildFeedXml({
      title: "t",
      publicBaseUrl: "https://x",
      episodes: [],
    });
    expect(xml).toContain("<channel>");
    expect(xml).toContain("<description>");
    expect(xml).not.toContain("<item>");
  });

  test("a custom description is escaped", () => {
    const xml = buildFeedXml({
      title: "t",
      publicBaseUrl: "https://x",
      episodes: [],
      description: "Takes & <tests>",
    });
    expect(xml).toContain(
      "<description>Takes &amp; &lt;tests&gt;</description>",
    );
  });
});

const baseFields = {
  role: "delivery" as const,
  metadataStripped: true,
  status: "pending" as const,
  encoding: {
    codec: "mp3" as const,
    bitrateKbps: 128,
    sampleRate: 48000,
    channels: 2,
  },
  normalization: "applied" as const,
  refs: {},
  createdBy: "system" as const,
};

describe("podcast.listFeedEpisodes", () => {
  test("returns only ready feed-access episodes with storage url and blob size", async () => {
    const t = convexTest(schema, modules);
    const blob = new Blob(["0123456789abcdef"]);

    const insertReady = async (
      fields: Pick<
        AudioArtifactInput,
        "kind" | "access" | "title" | "contentHash"
      >,
    ) => {
      const artifactId = await t.mutation(
        internal.audioArtifacts.createPending,
        {
          fields: { ...baseFields, ...fields },
        },
      );
      const storageId = await t.run((ctx) => ctx.storage.store(blob));
      await t.mutation(internal.audioArtifacts.attachStorage, {
        artifactId,
        storageId,
      });
      await t.mutation(internal.audioArtifacts.markReady, {
        artifactId,
        durationSecs: 12.4,
        loudnessLufs: -16,
        truePeakDbtp: -1,
        mimeType: "audio/mpeg",
      });
      return artifactId;
    };

    const feedEpisodeId = await insertReady({
      kind: "episode",
      access: "feed",
      title: "Feed episode",
      contentHash: "h-feed-episode",
    });
    await insertReady({
      kind: "episode",
      access: "private",
      title: "Private episode",
      contentHash: "h-private-episode",
    });
    await insertReady({
      kind: "probe",
      access: "feed",
      title: "Feed probe",
      contentHash: "h-feed-probe",
    });

    // A newer pending feed episode must not crowd the ready one out of the
    // window: the limit applies to ready rows only.
    await t.mutation(internal.audioArtifacts.createPending, {
      fields: {
        ...baseFields,
        kind: "episode",
        access: "feed",
        title: "Pending episode",
        contentHash: "h-pending-episode",
      },
    });
    const limited = await t.query(internal.podcast.listFeedEpisodes, {
      limit: 1,
    });
    expect(limited.map((row) => row.id)).toEqual([feedEpisodeId]);

    const episodes = await t.query(internal.podcast.listFeedEpisodes, {});
    expect(episodes).toHaveLength(1);
    const [episode] = episodes;
    expect(episode?.id).toBe(feedEpisodeId);
    expect(episode?.title).toBe("Feed episode");
    expect(episode?.sizeBytes).toBe(blob.size);
    expect(episode?.mimeType).toBe("audio/mpeg");
    expect(episode?.durationSecs).toBe(12.4);
    expect(episode?.storageUrl.startsWith("http")).toBe(true);

    // A blind-group member is never served, even with feed access.
    const blindId = await insertReady({
      kind: "episode",
      access: "feed",
      title: "Blind member",
      contentHash: "h-blind-member",
    });
    await t.run(async (ctx) => {
      const groupId = await ctx.db.insert("blindGroups", {
        purpose: "voiceShootout",
        members: [{ memberId: "m1", artifactId: blindId, label: "take one" }],
        requiredRatings: ["m1"],
        createdAt: Date.now(),
      });
      await ctx.db.patch(blindId, { blindGroupId: groupId });
    });
    const withBlind = await t.query(internal.podcast.listFeedEpisodes, {});
    expect(withBlind.map((row) => row.id)).toEqual([feedEpisodeId]);
  });

  test("a feed episode's WAV master is never an episode; only its delivery is served", async () => {
    const t = convexTest(schema, modules);
    const insertReady = async (
      fields: Pick<AudioArtifactInput, "role" | "title" | "contentHash"> & {
        masterArtifactId?: AudioArtifactInput["masterArtifactId"];
      },
    ) => {
      const artifactId = await t.mutation(
        internal.audioArtifacts.createPending,
        {
          fields: { ...baseFields, kind: "episode", access: "feed", ...fields },
        },
      );
      const storageId = await t.run((ctx) =>
        ctx.storage.store(new Blob([fields.contentHash])),
      );
      await t.mutation(internal.audioArtifacts.attachStorage, {
        artifactId,
        storageId,
      });
      await t.mutation(internal.audioArtifacts.markReady, {
        artifactId,
        durationSecs: 12.4,
        loudnessLufs: -16,
        truePeakDbtp: -1,
        mimeType: fields.role === "delivery" ? "audio/mpeg" : "audio/wav",
      });
      return artifactId;
    };
    // The master is newer than the delivery, so a role-blind feed would
    // list it first.
    const deliveryId = await insertReady({
      role: "delivery",
      title: "Episode",
      contentHash: "h-episode-delivery",
    });
    await insertReady({
      role: "masterNormalized",
      title: "Episode",
      contentHash: "h-episode-master",
    });
    const episodes = await t.query(internal.podcast.listFeedEpisodes, {});
    expect(episodes.map((row) => row.id)).toEqual([deliveryId]);
    expect(episodes[0]?.mimeType).toBe("audio/mpeg");
    // The master must not consume the window either: with room for one row
    // the delivery is still the row served.
    const limited = await t.query(internal.podcast.listFeedEpisodes, {
      limit: 1,
    });
    expect(limited.map((row) => row.id)).toEqual([deliveryId]);
  });
});

function stubFeedEnv() {
  vi.stubEnv("PODCAST_FEED_TOKEN", "test-token");
  vi.stubEnv("PODCAST_PUBLIC_BASE_URL", "https://listen.test");
}

describe("podcast feed route", () => {
  afterEach(() => vi.unstubAllEnvs());

  test("wrong token is a 404", async () => {
    stubFeedEnv();
    const t = convexTest(schema, modules);
    const response = await t.fetch("/podcast/wrong/feed.xml", {
      method: "GET",
    });
    expect(response.status).toBe(404);
  });

  test("right token serves an uncached rss channel", async () => {
    stubFeedEnv();
    const t = convexTest(schema, modules);
    const response = await t.fetch("/podcast/test-token/feed.xml", {
      method: "GET",
    });
    expect(response.status).toBe(200);
    expect(
      response.headers.get("content-type")?.startsWith("application/rss+xml"),
    ).toBe(true);
    expect(response.headers.get("cache-control")).toBe("no-store");
    expect(await response.text()).toContain("<channel>");
  });

  test("only feed.xml exists under the token", async () => {
    stubFeedEnv();
    const t = convexTest(schema, modules);
    const response = await t.fetch("/podcast/test-token/other", {
      method: "GET",
    });
    expect(response.status).toBe(404);
  });

  test("a ready feed episode is enclosed on the public host", async () => {
    stubFeedEnv();
    const t = convexTest(schema, modules);
    const artifactId = await t.mutation(internal.audioArtifacts.createPending, {
      fields: {
        ...baseFields,
        kind: "episode",
        access: "feed",
        title: "Feed episode",
        contentHash: "h-route-episode",
      },
    });
    const storageId = await t.run((ctx) =>
      ctx.storage.store(new Blob(["0123456789abcdef"])),
    );
    await t.mutation(internal.audioArtifacts.attachStorage, {
      artifactId,
      storageId,
    });
    await t.mutation(internal.audioArtifacts.markReady, {
      artifactId,
      durationSecs: 12.4,
      loudnessLufs: -16,
      truePeakDbtp: -1,
      mimeType: "audio/mpeg",
    });
    const response = await t.fetch("/podcast/test-token/feed.xml", {
      method: "GET",
    });
    expect(response.status).toBe(200);
    const xml = await response.text();
    expect(xml).toContain("<title>Feed episode</title>");
    expect(xml).toMatch(/<enclosure url="https:\/\/listen\.test\//);
    expect(xml).toContain(`<guid isPermaLink="false">${artifactId}</guid>`);
  });
});
