/* eslint-disable no-underscore-dangle -- Convex fixture ids are named `_id`. */
import { convexTest } from "convex-test";
import { describe, expect, test } from "vite-plus/test";
import { api } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { scoutConceptLimitPerDomain } from "./correspondences";
import schema from "./schema";
import { modules } from "../harness/modules";

describe("source scout target census", () => {
  test("shares the bounded concept budget across every scanned domain", () => {
    expect(scoutConceptLimitPerDomain(1)).toBe(50);
    expect(scoutConceptLimitPerDomain(4)).toBe(50);
    expect(scoutConceptLimitPerDomain(10)).toBe(20);
    expect(scoutConceptLimitPerDomain(50)).toBe(4);
  });

  test("returns the thinnest on-mission domains and oldest low-evidence conjectures", async () => {
    const t = convexTest(schema, modules);
    const seeded = await t.run(async (ctx) => {
      for (const [name, status] of [
        ["cymatics", "known"],
        ["psychoacoustics", "provisional"],
        ["wave-physics", "experimental"],
        ["empty-on-mission-domain", "known"],
        ["machine-learning", "deprecated"],
      ] as const) {
        await ctx.db.insert("conceptDomains", {
          name,
          status,
          introducedBy: "system",
          createdAt: 1,
          updatedAt: 1,
        });
      }

      const concepts = new Map<string, Id<"concepts">>();
      for (const [name, domain, missionRelevance] of [
        ["chladni-patterns", "cymatics", "on"],
        ["roughness", "psychoacoustics", "on"],
        ["critical-bands", "psychoacoustics", "on"],
        ["standing-waves", "wave-physics", "on"],
        ["optimizer", "machine-learning", "on"],
        ["spectral-model", "wave-physics", "off"],
      ] as const) {
        const id = await ctx.db.insert("concepts", {
          name,
          displayName: name,
          aliases: [],
          domain,
          missionRelevance,
          mentionCount: 0,
          hypothesisCount: 0,
          createdAt: 1,
          updatedAt: 1,
        });
        concepts.set(name, id);
      }

      for (const [conceptName, sourceIds] of [
        ["roughness", ["source-a", "source-a", "source-b"]],
        ["standing-waves", ["source-c"]],
      ] as const) {
        for (const sourceId of sourceIds) {
          await ctx.db.insert("edges", {
            fromType: "source",
            fromId: sourceId,
            toType: "concept",
            toId: conceptName,
            relationship: "mentions",
            autoGenerated: true,
            createdBy: "system",
            createdAt: 1,
          });
        }
      }

      const sourceId = await ctx.db.insert("sources", {
        type: "url",
        status: "extracted",
        dedupeKey: "scout-fixture-source",
        visibility: "private",
        createdBy: "system",
        createdAt: 1,
        updatedAt: 1,
      });
      const extractionId = await ctx.db.insert("extractions", {
        sourceId,
        model: "fixture",
        promptVersion: "fixture",
        inputHash: "fixture",
        summary: "fixture",
        claims: [],
        compositionParameters: [],
        topics: [],
        openQuestions: [],
        confidence: 1,
        createdBy: "system",
        createdAt: 1,
      });
      const claimId = await ctx.db.insert("claims", {
        extractionId,
        sourceId,
        ordinal: 0,
        text: "Fixture evidence",
        evidenceLevel: "peer_reviewed",
        citations: [],
        status: "active",
        createdBy: "system",
        createdAt: 1,
      });

      const makeCorrespondence = async (
        statement: string,
        updatedAt: number,
        evidence: Array<{
          claimId: typeof claimId;
          stance: "supports";
          addedBy: "agent";
          addedAt: number;
        }> = [],
      ) =>
        await ctx.db.insert("correspondences", {
          conceptAId: concepts.get("chladni-patterns")!,
          conceptBId: concepts.get("roughness")!,
          pairKey: `${statement}:pair`,
          statement,
          rationaleMd: "fixture rationale",
          evidence,
          status: "conjectured",
          createdBy: "system",
          createdAt: updatedAt,
          updatedAt,
        });

      const olderWithEvidence = await makeCorrespondence(
        "older with evidence",
        1,
        [{ claimId, stance: "supports", addedBy: "agent", addedAt: 1 }],
      );
      const oldestStarved = await makeCorrespondence("oldest starved", 2);
      const newerStarved = await makeCorrespondence("newer starved", 3);
      return { olderWithEvidence, oldestStarved, newerStarved };
    });

    const targets = await t.query(api.correspondences.scoutTargets, {});

    expect(targets.thinDomains).toEqual([
      { domain: "cymatics", onMissionConceptCount: 1, sourceCount: 0 },
      { domain: "wave-physics", onMissionConceptCount: 1, sourceCount: 1 },
      {
        domain: "psychoacoustics",
        onMissionConceptCount: 2,
        sourceCount: 2,
      },
    ]);
    expect(targets.starvedConjectures).toEqual([
      expect.objectContaining({
        correspondenceId: seeded.oldestStarved,
        statement: "oldest starved",
        conceptA: "chladni-patterns",
        conceptB: "roughness",
        evidenceCount: 0,
      }),
      expect.objectContaining({
        correspondenceId: seeded.newerStarved,
        evidenceCount: 0,
      }),
      expect.objectContaining({
        correspondenceId: seeded.olderWithEvidence,
        evidenceCount: 1,
      }),
    ]);
  });
});
