import { describe, expect, test } from "vite-plus/test";
import { convexTest } from "convex-test";
import { api } from "../convex/_generated/api";
import schema from "../convex/schema";
import { modules } from "./modules";

describe("graph concept detail authorization", () => {
  test("workbench detail includes private links while the public variant filters them", async () => {
    const t = convexTest(schema, modules);
    const ids = await t.run(async (ctx) => {
      const conceptId = await ctx.db.insert("concepts", {
        name: "cymatics",
        displayName: "Cymatics",
        aliases: [],
        domain: "wave",
        mentionCount: 2,
        hypothesisCount: 0,
        createdAt: 1,
        updatedAt: 1,
      });
      const publicSourceId = await ctx.db.insert("sources", {
        type: "url",
        title: "Public source",
        canonicalUrl: "https://example.com/public",
        dedupeKey: "url:example.com/public",
        status: "triaged",
        visibility: "public",
        createdBy: "system",
        createdAt: 1,
        updatedAt: 1,
      });
      const privateSourceId = await ctx.db.insert("sources", {
        type: "url",
        title: "Private source",
        canonicalUrl: "https://example.com/private",
        dedupeKey: "url:example.com/private",
        status: "triaged",
        visibility: "private",
        createdBy: "system",
        createdAt: 1,
        updatedAt: 1,
      });
      for (const sourceId of [publicSourceId, privateSourceId]) {
        await ctx.db.insert("edges", {
          fromType: "source",
          fromId: sourceId,
          toType: "concept",
          toId: "cymatics",
          relationship: "mentions",
          autoGenerated: true,
          createdAt: 1,
          createdBy: "system",
        });
      }
      return { conceptId };
    });

    const publicDetail = await t.query(api.graph.getConceptDetailPublic, ids);
    expect(publicDetail?.linkedSources.map((source) => source.title)).toEqual([
      "Public source",
    ]);

    const anonymousDetail = await t.query(api.graph.getConceptDetail, ids);
    expect(anonymousDetail?.linkedSources.map((source) => source.title)).toEqual(
      ["Public source"],
    );
    const workbenchDetail = await t
      .withIdentity({ subject: "user-1" })
      .query(api.graph.getConceptDetail, ids);
    expect(
      workbenchDetail?.linkedSources.map((source) => source.title).toSorted(),
    ).toEqual(["Private source", "Public source"]);
  });

  test("concept detail bounds its edge scan to the linked-item cap", async () => {
    const t = convexTest(schema, modules);
    const ids = await t.run(async (ctx) => {
      const conceptId = await ctx.db.insert("concepts", {
        name: "bounded-concept",
        displayName: "Bounded concept",
        aliases: [],
        domain: "general",
        mentionCount: 25,
        hypothesisCount: 0,
        createdAt: 1,
        updatedAt: 1,
      });
      for (let index = 0; index < 25; index++) {
        const sourceId = await ctx.db.insert("sources", {
          type: "url",
          title: `Source ${index}`,
          dedupeKey: `url:example.com/bounded-${index}`,
          status: "triaged",
          visibility: "public",
          createdBy: "system",
          createdAt: index + 1,
          updatedAt: index + 1,
        });
        await ctx.db.insert("edges", {
          fromType: "source",
          fromId: sourceId,
          toType: "concept",
          toId: "bounded-concept",
          relationship: "mentions",
          autoGenerated: true,
          createdAt: index + 1,
          createdBy: "system",
        });
      }
      return { conceptId };
    });

    const detail = await t.query(api.graph.getConceptDetailPublic, ids);
    expect(detail?.edgeCount).toBe(20);
    expect(detail?.linkedSources).toHaveLength(20);
  });
});
