// Hand-rolled replacement for import.meta.glob("./**/*.ts") (bun has no glob).
// Keys are paths as if globbed from inside convex/; values are lazy thunks.
// Excludes *.test.ts, testHelpers.ts, and harness/. The generated sentinel is
// required so convex-test can derive the module root; it is never registered.
export const modules: Record<string, () => Promise<unknown>> = {
  "./_generated/api.d.ts": () => import("../convex/_generated/api"),
  "./admin.ts": () => import("../convex/admin"),
  "./agentDraftPromotion.ts": () => import("../convex/agentDraftPromotion"),
  "./agentDrafts.ts": () => import("../convex/agentDrafts"),
  "./agentRuns.ts": () => import("../convex/agentRuns"),
  "./agentTools.ts": () => import("../convex/agentTools"),
  "./agentToolsHttp.ts": () => import("../convex/agentToolsHttp"),
  "./aggregates.ts": () => import("../convex/aggregates"),
  "./auth.ts": () => import("../convex/auth"),
  "./campaigns.ts": () => import("../convex/campaigns"),
  "./claims.ts": () => import("../convex/claims"),
  "./components.ts": () => import("../convex/components"),
  "./compositions.ts": () => import("../convex/compositions"),
  "./conceptClassifier.ts": () => import("../convex/conceptClassifier"),
  "./conceptClassifierInternal.ts": () =>
    import("../convex/conceptClassifierInternal"),
  "./crons.ts": () => import("../convex/crons"),
  "./dashboard.ts": () => import("../convex/dashboard"),
  "./domainMappings.ts": () => import("../convex/domainMappings"),
  "./editCaptures.ts": () => import("../convex/editCaptures"),
  "./editorialArtifacts.ts": () => import("../convex/editorialArtifacts"),
  "./editorialExports.ts": () => import("../convex/editorialExports"),
  "./extract.ts": () => import("../convex/extract"),
  "./extractInternal.ts": () => import("../convex/extractInternal"),
  "./extractions.ts": () => import("../convex/extractions"),
  "./fabric.ts": () => import("../convex/fabric"),
  "./failures.ts": () => import("../convex/failures"),
  "./feeds.ts": () => import("../convex/feeds"),
  "./graph.ts": () => import("../convex/graph"),
  "./http.ts": () => import("../convex/http"),
  "./hypotheses.ts": () => import("../convex/hypotheses"),
  "./hypothesesInternal.ts": () => import("../convex/hypothesesInternal"),
  "./inbox.ts": () => import("../convex/inbox"),
  "./ingest.ts": () => import("../convex/ingest"),
  "./listening.ts": () => import("../convex/listening"),
  "./phase2.ts": () => import("../convex/phase2"),
  "./recipes.ts": () => import("../convex/recipes"),
  "./recipesInternal.ts": () => import("../convex/recipesInternal"),
  "./schema.ts": () => import("../convex/schema"),
  "./sources.ts": () => import("../convex/sources"),
  "./sourceUtils.ts": () => import("../convex/sourceUtils"),
  "./testing.ts": () => import("../convex/testing"),
  "./theses.ts": () => import("../convex/theses"),
  "./tracing.ts": () => import("../convex/tracing"),
  "./validators.ts": () => import("../convex/validators"),
  "./vocabulary.ts": () => import("../convex/vocabulary"),
  "./weeklyBriefs.ts": () => import("../convex/weeklyBriefs"),
  "./weeklyBriefsInternal.ts": () => import("../convex/weeklyBriefsInternal"),
  "./workflows.ts": () => import("../convex/workflows"),
};
