// Hand-rolled replacement for import.meta.glob("./**/*.ts") (bun has no glob).
// Keys are paths as if globbed from inside convex/; values are lazy thunks.
// Excludes *.test.ts, testHelpers.ts, and harness/. The generated sentinel is
// required so convex-test can derive the module root; it is never registered.
export const modules: Record<string, () => Promise<unknown>> = {
  "./_generated/api.d.ts": () => import("../convex/_generated/api"),
  "./admin.ts": () => import("../convex/admin"),
  "./agentDraftPromotion.ts": () => import("../convex/agentDraftPromotion"),
  "./agentDrafts.ts": () => import("../convex/agentDrafts"),
  "./agentRuns.ts": () => import("../convex/agentRuns"),
  "./agentTools.ts": () => import("../convex/agentTools"),
  "./agentToolsHttp.ts": () => import("../convex/agentToolsHttp"),
  "./aggregates.ts": () => import("../convex/aggregates"),
  "./audioArtifacts.ts": () => import("../convex/audioArtifacts"),
  "./auth.ts": () => import("../convex/auth"),
  "./blindGroups.ts": () => import("../convex/blindGroups"),
  "./campaigns.ts": () => import("../convex/campaigns"),
  "./claims.ts": () => import("../convex/claims"),
  "./components.ts": () => import("../convex/components"),
  "./compositions.ts": () => import("../convex/compositions"),
  "./conceptClassifier.ts": () => import("../convex/conceptClassifier"),
  "./conceptClassifierInternal.ts": () =>
    import("../convex/conceptClassifierInternal"),
  "./correspondences.ts": () => import("../convex/correspondences"),
  "./correspondenceCandidates.ts": () =>
    import("../convex/correspondenceCandidates"),
  "./crons.ts": () => import("../convex/crons"),
  "./dashboard.ts": () => import("../convex/dashboard"),
  "./domainMappings.ts": () => import("../convex/domainMappings"),
  "./editCaptures.ts": () => import("../convex/editCaptures"),
  "./editorialArtifacts.ts": () => import("../convex/editorialArtifacts"),
  "./editorialExports.ts": () => import("../convex/editorialExports"),
  "./embeddings.ts": () => import("../convex/embeddings"),
  "./embeddingsStore.ts": () => import("../convex/embeddingsStore"),
  "./episodes.ts": () => import("../convex/episodes"),
  "./extract.ts": () => import("../convex/extract"),
  "./extractInternal.ts": () => import("../convex/extractInternal"),
  "./extractions.ts": () => import("../convex/extractions"),
  "./fabric.ts": () => import("../convex/fabric"),
  "./failures.ts": () => import("../convex/failures"),
  "./feeds.ts": () => import("../convex/feeds"),
  "./graph.ts": () => import("../convex/graph"),
  "./http.ts": () => import("../convex/http"),
  "./hypotheses.ts": () => import("../convex/hypotheses"),
  "./hypothesesInternal.ts": () => import("../convex/hypothesesInternal"),
  "./inbox.ts": () => import("../convex/inbox"),
  "./ingest.ts": () => import("../convex/ingest"),
  "./listen.ts": () => import("../convex/listen"),
  "./listening.ts": () => import("../convex/listening"),
  "./mediaJobEffects.ts": () => import("../convex/mediaJobEffects"),
  "./mediaJobs.ts": () => import("../convex/mediaJobs"),
  "./mediaSweeper.ts": () => import("../convex/mediaSweeper"),
  "./mediaToolsInternal.ts": () => import("../convex/mediaToolsInternal"),
  "./narration.ts": () => import("../convex/narration"),
  "./narrationPrompt.ts": () => import("../convex/narrationPrompt"),
  "./phase2.ts": () => import("../convex/phase2"),
  "./podcast.ts": () => import("../convex/podcast"),
  "./recipes.ts": () => import("../convex/recipes"),
  "./recipesInternal.ts": () => import("../convex/recipesInternal"),
  "./schema.ts": () => import("../convex/schema"),
  "./settings.ts": () => import("../convex/settings"),
  "./sources.ts": () => import("../convex/sources"),
  "./sourceUtils.ts": () => import("../convex/sourceUtils"),
  "./testing.ts": () => import("../convex/testing"),
  "./theses.ts": () => import("../convex/theses"),
  "./tracing.ts": () => import("../convex/tracing"),
  "./validators.ts": () => import("../convex/validators"),
  "./vocabulary.ts": () => import("../convex/vocabulary"),
  "./voiceRatings.ts": () => import("../convex/voiceRatings"),
  "./weeklyBriefs.ts": () => import("../convex/weeklyBriefs"),
  "./weeklyBriefsInternal.ts": () => import("../convex/weeklyBriefsInternal"),
  "./workflows.ts": () => import("../convex/workflows"),
};
