// Hand-rolled replacement for import.meta.glob("./**/*.ts") (bun has no glob).
// Keys are paths as if globbed from inside convex/; values are lazy thunks.
// Excludes *.test.ts, testHelpers.ts, and harness/. The generated sentinel is
// required so convex-test can derive the module root; it is never registered.
export const modules: Record<string, () => Promise<unknown>> = {
  "./_generated/api.d.ts": () => import("../_generated/api"),
  "./admin.ts": () => import("../admin"),
  "./agentDraftPromotion.ts": () => import("../agentDraftPromotion"),
  "./agentDrafts.ts": () => import("../agentDrafts"),
  "./agentRuns.ts": () => import("../agentRuns"),
  "./agentTools.ts": () => import("../agentTools"),
  "./agentToolsHttp.ts": () => import("../agentToolsHttp"),
  "./aggregates.ts": () => import("../aggregates"),
  "./auth.ts": () => import("../auth"),
  "./campaigns.ts": () => import("../campaigns"),
  "./components.ts": () => import("../components"),
  "./compositions.ts": () => import("../compositions"),
  "./crons.ts": () => import("../crons"),
  "./dashboard.ts": () => import("../dashboard"),
  "./domainMappings.ts": () => import("../domainMappings"),
  "./editCaptures.ts": () => import("../editCaptures"),
  "./editorialArtifacts.ts": () => import("../editorialArtifacts"),
  "./editorialExports.ts": () => import("../editorialExports"),
  "./extract.ts": () => import("../extract"),
  "./extractInternal.ts": () => import("../extractInternal"),
  "./extractions.ts": () => import("../extractions"),
  "./fabric.ts": () => import("../fabric"),
  "./failures.ts": () => import("../failures"),
  "./feeds.ts": () => import("../feeds"),
  "./graph.ts": () => import("../graph"),
  "./http.ts": () => import("../http"),
  "./hypotheses.ts": () => import("../hypotheses"),
  "./hypothesesInternal.ts": () => import("../hypothesesInternal"),
  "./inbox.ts": () => import("../inbox"),
  "./ingest.ts": () => import("../ingest"),
  "./listening.ts": () => import("../listening"),
  "./phase2.ts": () => import("../phase2"),
  "./recipes.ts": () => import("../recipes"),
  "./recipesInternal.ts": () => import("../recipesInternal"),
  "./schema.ts": () => import("../schema"),
  "./sources.ts": () => import("../sources"),
  "./sourceUtils.ts": () => import("../sourceUtils"),
  "./testing.ts": () => import("../testing"),
  "./theses.ts": () => import("../theses"),
  "./tracing.ts": () => import("../tracing"),
  "./validators.ts": () => import("../validators"),
  "./vocabulary.ts": () => import("../vocabulary"),
  "./weeklyBriefs.ts": () => import("../weeklyBriefs"),
  "./weeklyBriefsInternal.ts": () => import("../weeklyBriefsInternal"),
  "./workflows.ts": () => import("../workflows"),
};
